# Generated by Django 5.1.3 on 2026-05-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=250, unique=True)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('responsabledni', models.IntegerField(blank=True)),
                ('domicilio', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contratistas',
            },
        ),
    ]
