# Generated by Django 5.1.3 on 2026-05-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratista",
            name="responsabledni",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
