# Generated by Django 5.1.3 on 2026-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('V', 'Varios'), ('M', 'Materiales'), ('C', 'Certificado'), ('A', 'Contrato o Alquiler')], default='T', max_length=1, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('V', 'Varios'), ('M', 'Materiales'), ('C', 'Certificado'), ('A', 'Contrato o Alquiler')], default='V', max_length=1, null=True)),
                ('fechanota', models.DateField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, default=None, max_length=10, null=True, unique=True)),
                ('fechaexpediente', models.DateField(blank=True, null=True)),
                ('nomenclatura', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('decreto', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('fechadecreto', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, default=None, max_length=5000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Documentaciones',
            },
        ),
    ]
