# Generated by Django 5.1.3 on 2026-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentacion",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("T", "En tramite"),
                    ("P", "Pagado"),
                    ("N", "Notificado"),
                    ("A", "Archivado"),
                ],
                default="T",
                max_length=1,
                null=True,
            ),
        ),
    ]
