# Generated by Django 5.1.3 on 2026-05-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0002_alter_contratista_responsabledni'),
        ('documentaciones', '0002_alter_documentacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratistas.contratista'),
        ),
    ]
