# Generated by Django 5.1.3 on 2026-06-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentaciones', '0003_documentacion_contratista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('V', 'Varios'), ('M', 'Materiales'), ('C', 'Certificado'), ('A', 'Contrato o Alquiler'), ('P', 'Pago Servicios')], default='V', max_length=1, null=True),
        ),
    ]
