# Generated by Django 5.1.3 on 2026-05-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Materiales',
            },
        ),
    ]
