# Generated by Django 5.1.3 on 2026-06-11 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratistas', '0002_alter_contratista_responsabledni'),
        ('documentaciones', '0004_alter_documentacion_tipo'),
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('textodestinatario', models.CharField(blank=True, max_length=250, null=True)),
                ('textodestino', models.CharField(blank=True, max_length=250, null=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratistas.contratista')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentaciones.documentacion')),
            ],
            options={
                'verbose_name_plural': 'Remitos',
            },
        ),
        migrations.CreateModel(
            name='DetalleRemito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remitos.remito')),
            ],
            options={
                'verbose_name_plural': 'Detalles Remito',
            },
        ),
    ]
