# Generated by Django 5.2 on 2026-07-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_unidad'),
        ('remitos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremito',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiales.unidad'),
        ),
    ]
