# Generated by Django 5.2 on 2026-08-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0002_detalleremito_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='numerosop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
